# Generated by Django 4.2.5 on 2026-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('planning', 'Plan to Watch'), ('completed', 'Completed'), ('paused', 'On Hold'), ('dropped', 'Dropped')], default='planning', max_length=20)),
            ],
        ),
    ]
