# Generated by Django 4.2.5 on 2026-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_animelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
