# Generated by Django 4.2.5 on 2026-04-16 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_animelist_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
