# Generated by Django 4.2.5 on 2026-04-16 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_animelist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='progress',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
