# Generated by Django 4.2.5 on 2026-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_animelist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('planning', 'Plan to Watch'), ('completed', 'Completed'), ('paused', 'On Hold'), ('dropped', 'Dropped')], default='planning', max_length=20, null=True),
        ),
    ]
