# Generated by Django 4.2.5 on 2026-04-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_animelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='total_episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
