# Generated by Django 4.2.5 on 2026-04-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_animelist_total_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='animelist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='animelist',
            name='total_episodes',
        ),
    ]
