# Generated by Django 4.2.5 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_remove_animelist_image_url_remove_animelist_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='total_episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
